### ISSUE TITLE
Rich push notification not tracking opened on targetSDK > 30

### ISSUE THREAD

**Issue by matthieuMay** [customerio/customerio-android#166]
**SDK version:** 
3.2.0-alpha2

**Environment:** 
Development and Production

**Are logs available?** 

**Describe the bug**
The rich notifications are never seen as opened by the android SDK if target SDK is greater than 30

**To Reproduce**
Try rich push with an application with target SDK set to 33

**Additional context**
The problem is situated in io.customer.messagingpush.CustomerIOPushNotificationHandler#createIntentFromLink. If the targetSDK is higher than 30, io.customer.messagingpush.util.DeepLinkUtilImpl#queryDeepLinksForHostApp is called and this creates an intent with ACTION_VIEW and not a CustomerIOPushReceiver.ACTION intent

Note that this notifications also restart applications using android:launchMode="singleTask" which probably would defeat the tracking anyway because the CustomerIO SDK may not be initialized before the broadcastReceiver is executed.

**Comment by mrehan27** [comment]
Hi @matthieuMay. I believe this is expected behavior from Android 12 and onwards, please read [our docs on deep links](https://www.customer.io/docs/sdk/android/push/#deep-links) and let us know if you have more questions.

We recommend [initializing the SDK in Application class](https://www.customer.io/docs/sdk/android/getting-started/#initialize-the-sdk), so native apps can always guarantee CustomerIO SDK is initialized before any service or broadcast is called.

For applications using `singleTask`, I'm not yet sure if we tested with all launch modes, but I can confirm, it works fine for default `launchMode` and most cases. Quick test shows it works fine for `singleTask` as well. However, we'll test with more launch modes update the docs for clarity on it.

I tried running some quick tests and the tracking seems to be working fine for API level 33. Can you please answer following queries to help us reproduce and identify the issue:

- Are you adding the SDK in native Android app?
- Are you trying to open external link or link [registered by your app in AndroidManifest](https://developer.android.com/training/app-links/deep-linking#adding-filters)?
- Are you using any library for handling deep links? e.g. [Android Navigation](https://developer.android.com/guide/navigation)
- State of your app when notification received and opened i.e. Background, Foreground or Killed
- Can you share your logs here or see if you find anything useful in them? e.g. any errors or logs like `push metric delivered`, `push metric opened`, etc.
- Is your application has only one Activity? If yes, are you using Jetpack Compose or something else?
- Are using any `launchMode` in your deep linked Activity?

Also, please note that metrics are only tracked for Campaigns and not for test notifications.

**Comment by matthieuMay** [comment]
@mrehan27 I probably should have precised that I use react-native wrapping. In this wrapping the initializattion of Customer.io SDK is made after the BroadcastReceiver is called and therefore the metrics are not saved

Anyway, I found another solution satisfying my needs so you can close this issue

**Comment by mrehan27** [comment]
Thanks for the update @matthieuMay. Glad you found a working solution to solve the issue.
